### ISSUE TITLE
Event not changing the content of the sign

### ISSUE THREAD

**Issue by CarinaSchoppe** [blablubbabc/IndividualSigns#9]
Hey folks,
ive tried to get the plugin up and running with my own adaptation but even the basic plugin doesnt seem to change the [PLAYER] line to the users line in the latest papermc version (1.21.1) with protocollib

**Comment by blablubbabc** [comment]
The latest released version of the plugin doesn't include this fix for 1.20 yet: https://github.com/blablubbabc/IndividualSigns/commit/a9bc102cd92cfd16dbd200f745969f7ce5c2804a

Will prepare an update.

**Comment by CarinaSchoppe** [comment]
Hey, thanks for the quick reply. 
So just compile the src and I would be good to go?

**Comment by blablubbabc** [comment]
Yes. If you are building with JDK 21 you also need to update the Gradle wrapper version to e.g. 8.5

**Comment by blablubbabc** [comment]
I have uploaded an update to dev.bukkit.org, which is currently pending review, but should be available within the next few days. Alternatively, you can also build the plugin yourself from source. Edit: Or get it from Jitpack: https://jitpack.io/com/github/blablubbabc/IndividualSigns/v2.9.2/IndividualSigns-v2.9.2.jar
